apiVersion: apps/v1
kind: Deployment
metadata:
  name: session
spec:
  template:
    spec:
      volumes:
        - name: gitrepo
          emptyDir: {}
      containers:
      - name: dev
        volumeMounts:
          - mountPath: /root/workshop
            name: gitrepo 
