apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-lister
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lister
subjects:
- kind: ServiceAccount
  name: sa
  namespace: workshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-ssh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sshreader
subjects:
- kind: ServiceAccount
  name: sa
  namespace: workshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: common-config
subjects:
- kind: ServiceAccount
  name: sa
  namespace: workshop